package tokyo.aieuo.mineflow.flowItem

object FlowItemIds {

    const val DO_NOTHING = "doNothing"
    const val GET_DATE = "getDate"
    const val EVENT_CANCEL = "eventCancel"
    const val CALL_CUSTOM_TRIGGER = "callTrigger"
    const val SEND_FORM = "sendForm"

    const val SEND_MESSAGE = "sendMessage"
    const val SEND_TIP = "sendTip"
    const val SEND_POPUP = "sendPopup"
    const val BROADCAST_MESSAGE = "broadcastMessage"
    const val SEND_MESSAGE_TO_OP = "sendMessageToOp"
    const val SEND_MESSAGE_TO_CONSOLE = "sendMessageToConsole"
    const val SEND_TITLE = "sendTitle"

    const val GET_ENTITY = "getEntity"
    const val TELEPORT = "teleport"
    const val MOTION = "motion"
    const val SET_YAW = "setYaw"
    const val SET_PITCH = "setPitch"
    const val ADD_DAMAGE = "addDamage"
    const val SET_IMMOBILE = "setImmobile"
    const val UNSET_IMMOBILE = "unsetImmobile"
    const val SET_HEALTH = "setHealth"
    const val SET_MAX_HEALTH = "setMaxHealth"
    const val SET_NAME = "setName"
    const val SET_SCALE = "setScale"
    const val ADD_EFFECT = "addEffect"
    const val ADD_XP_PROGRESS = "addXp"
    const val ADD_XP_LEVEL = "addXpLevel"
    const val GET_TARGET_BLOCK = "getTargetBlock"
    const val CREATE_HUMAN_ENTITY = "createHuman"
    const val GET_ENTITY_SIDE = "getEntitySide"
    const val LOOK_AT = "lookAt"
    const val MOVE_TO = "moveTo"

    const val GET_PLAYER = "getPlayer"
    const val SET_SLEEPING = "setSleeping"
    const val SET_SITTING = "setSitting"
    const val KICK = "kick"
    const val CLEAR_INVENTORY = "clearInventory"
    const val SET_FOOD = "setFood"
    const val SET_GAMEMODE = "setGamemode"
    const val SHOW_BOSSBAR = "showBossbar"
    const val REMOVE_BOSSBAR = "removeBossbar"
    const val SHOW_SCOREBOARD = "showScoreboard"
    const val HIDE_SCOREBOARD = "hideScoreboard"
    const val PLAY_SOUND = "playSound"
    const val PLAY_SOUND_AT = "playSoundAt"
    const val ADD_PERMISSION = "addPermission"
    const val REMOVE_PERMISSION = "removePermission"
    const val ALLOW_FLIGHT = "allowFlight"
    const val ALLOW_CLIMB_WALLS = "allowClimbWalls"

    const val ADD_MONEY = "addMoney"
    const val SET_MONEY = "setMoney"
    const val TAKE_MONEY = "takeMoney"
    const val GET_MONEY = "getMoney"

    const val ADD_ITEM = "addItem"
    const val REMOVE_ITEM = "removeItem"
    const val REMOVE_ITEM_ALL = "removeItemAll"
    const val SET_ITEM = "setItem"
    const val SET_ITEM_IN_HAND = "setItemInHand"
    const val ADD_ENCHANTMENT = "addEnchant"
    const val SET_ITEM_LORE = "setLore"
    const val SET_ITEM_DAMAGE = "setItemDamage"
    const val SET_ITEM_COUNT = "setItemCount"
    const val SET_ITEM_NAME = "setItemName"
    const val EQUIP_ARMOR = "equipArmor"
    const val GET_INVENTORY_CONTENTS = "getInventory"
    const val GET_ARMOR_INVENTORY_CONTENTS = "getArmorInventory"

    const val COMMAND = "command"
    const val COMMAND_CONSOLE = "commandConsole"

    const val SET_BLOCK = "setBlock"
    const val GET_BLOCK = "getBlock"
    const val ADD_PARTICLE = "addParticle"
    const val SET_WEATHER = "setWeather"
    const val GET_DISTANCE = "getDistance"
    const val DROP_ITEM = "dropItem"
    const val GENERATE_RANDOM_POSITION = "randomPosition"
    const val POSITION_VARIABLE_ADDITION = "positionAddition"

    const val EXECUTE_RECIPE = "executeRecipe"
    const val EXECUTE_IF_CHAIN = "executeIFChain"
    const val EXECUTE_RECIPE_WITH_ENTITY = "executeRecipeWithEntity"
    const val CALL_RECIPE = "callRecipe"

    const val FOUR_ARITHMETIC_OPERATIONS = "fourArithmeticOperations"
    const val FOUR_ARITHMETIC_OPERATIONS_ADD = "add"
    const val FOUR_ARITHMETIC_OPERATIONS_SUB = "sub"
    const val FOUR_ARITHMETIC_OPERATIONS_MUL = "mul"
    const val FOUR_ARITHMETIC_OPERATIONS_DIV = "div"
    const val CALCULATE = "calculate"
    const val CALCULATE_SIN = "sin"
    const val CALCULATE_COS = "cos"
    const val CALCULATE_TAN = "tan"
    const val CALCULATE_FLOOR = "floor"
    const val CALCULATE_CEIL = "ceil"
    const val CALCULATE2 = "calculate2"
    const val CALCULATE2_ROUND = "round"
    const val GET_PI = "getPi"
    const val GET_E = "getE"
    const val GENERATE_RANDOM_NUMBER = "random"
    const val REVERSE_POLISH_NOTATION = "calculateRPN"

    const val EDIT_STRING = "editString"
    const val STRING_LENGTH = "strlen"

    const val ADD_VARIABLE = "addVariable"
    const val DELETE_VARIABLE = "deleteVariable"
    const val ADD_LIST_VARIABLE = "addListVariable"
    const val JOIN_LIST_VARIABLE_TO_STRING = "joinToString"
    const val CREATE_LIST_VARIABLE = "createList"
    const val ADD_MAP_VARIABLE = "addMapVariable"
    const val CREATE_MAP_VARIABLE = "createMap"
    const val CREATE_MAP_VARIABLE_FROM_JSON = "createMapFromJson"
    const val CREATE_ITEM_VARIABLE = "createItem"
    const val CREATE_POSITION_VARIABLE = "createPosition"
    const val CREATE_BLOCK_VARIABLE = "createBlock"
    const val GET_VARIABLE_NESTED = "getVariable"
    const val COUNT_LIST_VARIABLE = "count"
    const val GET_LIST_KEYS = "keys"
    const val GET_LIST_VALUES = "values"
    const val SEARCH_LIST_KEY = "searchKey"
    const val DELETE_LIST_VARIABLE_CONTENT = "removeContent"
    const val CREATE_SCOREBOARD_VARIABLE = "createScoreboard"

    const val ACTION_IF = "if"
    const val ACTION_ELSEIF = "elseif"
    const val ACTION_ELSE = "else"
    const val ACTION_REPEAT = "repeat"
    const val ACTION_WHILE = "while"
    const val ACTION_WAIT = "wait"
    const val ACTION_FOR = "for"
    const val FOREACH_POSITION = "foreachPosition"
    const val ACTION_FOREACH = "foreach"
    const val SAVE_DATA = "save"
    const val ACTION_WHILE_TASK = "whileTask"
    const val CREATE_CONFIG_VARIABLE = "createConfig"
    const val SET_CONFIG_VALUE = "setConfig"
    const val SAVE_CONFIG_FILE = "saveConfig"
    const val REMOVE_CONFIG_VALUE = "removeConfig"
    const val EXIT_RECIPE = "exit"
    const val EXIT_CONTAINER = "break"

    const val SEND_INPUT = "input"
    const val SEND_MENU = "select"
    const val SEND_SLIDER = "slider"
    const val SEND_DROPDOWN = "dropdown"

    const val SET_SCOREBOARD_SCORE = "setScore"
    const val SET_SCOREBOARD_SCORE_NAME = "setScoreName"
    const val REMOVE_SCOREBOARD_SCORE = "removeScore"
    const val REMOVE_SCOREBOARD_SCORE_NAME = "removeScoreName"
    const val INCREMENT_SCOREBOARD_SCORE = "incrementScore"
    const val DECREMENT_SCOREBOARD_SCORE = "decrementScore"

    const val REGISTER_SHAPED_RECIPE = "registerShapedRecipe"


    /* condition */
    const val CHECK_NOTHING = "checkNothing"
    const val IS_OP = "isOp"
    const val IS_SNEAKING = "isSneaking"
    const val IS_FLYING = "isFlying"
    const val IN_AREA = "inArea"
    const val GAMEMODE = "gamemode"
    const val HAS_PERMISSION = "hasPermission"

    const val OVER_MONEY = "overMoney"
    const val LESS_MONEY = "lessMoney"
    const val TAKE_MONEY_CONDITION = "takeMoneyCondition"

    const val CAN_ADD_ITEM = "canAddItem"
    const val EXISTS_ITEM = "existsItem"
    const val IN_HAND = "isHandItem"
    const val REMOVE_ITEM_CONDITION = "removeItemCondition"

    const val COMPARISON_NUMBER = "comparisonNumber"
    const val COMPARISON_STRING = "comparisonString"

    const val IS_ACTIVE_ENTITY = "isActiveEntity"
    const val IS_ACTIVE_ENTITY_VARIABLE = "isActiveEntityVariable"
    const val IS_PLAYER = "isPlayer"
    const val IS_PLAYER_VARIABLE = "isPlayerVariable"
    const val IS_PLAYER_ONLINE = "isPlayerOnline"
    const val IS_PLAYER_ONLINE_BY_NAME = "isPlayerOnlineByName"
    const val IS_CREATURE = "isCreature"
    const val IS_CREATURE_VARIABLE = "isCreatureVariable"

    const val EXISTS_VARIABLE = "existsVariable"
    const val EXISTS_LIST_VARIABLE_KEY = "existsListVariableKey"

    const val CONDITION_AND = "and"
    const val CONDITION_OR = "or"
    const val CONDITION_NAND = "nand"
    const val CONDITION_NOR = "nor"
    const val CONDITION_NOT = "not"
    const val EXISTS_CONFIG_FILE = "existsConfigFile"
    const val EXISTS_CONFIG_DATA = "existsConfig"

    const val RANDOM_NUMBER = "randomNumber"
}